[package]
name = "commit-boost"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
cb-cli.workspace = true
cb-common.workspace = true
cb-metrics.workspace = true
cb-pbs.workspace = true
cb-signer.workspace = true

# async / threads
tokio.workspace = true
async-trait.workspace = true

# serialization
serde_json.workspace = true

# crypto
tree_hash.workspace = true
tree_hash_derive.workspace = true

# telemetry
tracing.workspace = true
tracing-subscriber.workspace = true

# misc
clap.workspace = true

#chrono
chrono = "0.4.38"

[[bin]]
name = "commit-boost"
path = "commit_boost.rs"

[[bin]]
name = "default-pbs"
path = "default_pbs.rs"

[[bin]]
name = "signer-module"
path = "signer_module.rs"

[[bin]]
name = "logger"
path = "logger.rs"
