[package]
name = "cb-signer"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
cb-common.workspace = true

# ethereum
alloy.workspace = true
ethereum_ssz.workspace = true
ethereum_ssz_derive.workspace = true

# networking
axum.workspace = true
axum-extra.workspace = true
headers.workspace = true

# async / threads
tokio.workspace = true

# serialization
serde.workspace = true

# telemetry
tracing.workspace = true

# crypto
blst.workspace = true
tree_hash.workspace = true
tree_hash_derive.workspace = true

# misc
thiserror.workspace = true
eyre.workspace = true
rand.workspace = true
uuid.workspace = true
bimap.workspace = true
lazy_static.workspace = true
derive_more.workspace = true
