# PBS config with a mux for a single validator

chain = "Holesky"

[[pbs]]
port = 18550
timeout_get_header_ms = 950
late_in_slot_time_ms = 2000
rpc_url = "https://ethereum-holesky-rpc.publicnode.com"

# Used for all validators except the ones in the mux
[[relays]]
id = "relay-1"
url = "http://0xa1cec75a3f0661e99299274182938151e8433c61a19222347ea1313d839229cb4ce4e3e5aa2bdeb71c8fcf1b084963c2@abc.xyz"


[[mux]]
id = "timing-mux"
validator_pubkeys = [
    "0x80c7f782b2467c5898c5516a8b6595d75623960b4afc4f71ee07d40985d20e117ba35e7cd352a3e75fb85a8668a3b745",
]
loader = "./tests/data/mux_keys.example.json"
timeout_get_header_ms = 900
late_in_slot_time_ms = 1500


[[mux.relays]]
id = "relay-2"
url = "http://0xa119589bb33ef52acbb8116832bec2b58fca590fe5c85eac5d3230b44d5bc09fe73ccd21f88eab31d6de16194d17782e@def.xyz"
enable_timing_games = true
target_first_request_ms = 200


[[mux]]
id = "lido-mux"
loader = { registry = "lido", node_operator_id = 8 }

[[mux.relays]]
id = "relay-3"
url = "http://0x80c7f782b2467c5898c5516a8b6595d75623960b4afc4f71ee07d40985d20e117ba35e7cd352a3e75fb85a8668a3b745@fgh.xyz"

[[mux]]
id = "ssv-mux"
loader = { registry = "ssv", node_operator_id = 200 }

[[mux.relays]]
id = "relay-4"
url = "http://0x80c7f782b2467c5898c5516a8b6595d75623960b4afc4f71ee07d40985d20e117ba35e7cd352a3e75fb85a8668a3b745@fgh.xyz"
