[package]
name = "cb-pbs"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
cb-common.workspace = true
cb-crypto.workspace = true
cb-metrics.workspace = true

alloy-primitives.workspace = true
alloy-rpc-types-beacon.workspace = true

tokio.workspace = true
futures.workspace = true

axum.workspace = true
reqwest.workspace = true

tracing.workspace = true

async-trait.workspace = true

serde.workspace = true
serde_json.workspace = true
ethereum_ssz.workspace = true
ethereum_ssz_derive.workspace = true
ssz_types.workspace = true
typenum.workspace = true
ethereum_serde_utils.workspace = true
ethereum-types.workspace = true

dashmap.workspace = true

# crypto
blst.workspace = true
tree_hash.workspace = true
tree_hash_derive.workspace = true

eyre.workspace = true
thiserror.workspace = true
uuid.workspace = true

lazy_static.workspace = true
prometheus.workspace = true

[dev-dependencies]
tracing-subscriber.workspace = true
